### ISSUE TITLE
All tags should be within the body tag

### ISSUE THREAD

**Issue by TheByteSizeDev** [ChaseBurnett/E20-Daily-Journal-Project#2]
All tags should be within the body tag including the `<main></main>`  tag. See the article below.

[Main vs Body Tags](https://www.tutorialstonight.com/main-vs-body-html)

https://github.com/ChaseBurnett/E20-Daily-Journal-Project/blob/d48f17dd1228acdc02ed696744ec497b3dd0b152/index.html#L15-L16

**Comment by ChaseBurnett** [comment]
Ignore my previous question!
