### ISSUE TITLE
Footer can be outside of main but...

### ISSUE THREAD

**Issue by TheByteSizeDev** [ChaseBurnett/E20-Daily-Journal-Project#3]
Footer can be outside of main but both the `<main>` and the  `<footer>` tag should be inside of the `<body>' tag.

https://github.com/ChaseBurnett/E20-Daily-Journal-Project/blob/d48f17dd1228acdc02ed696744ec497b3dd0b152/index.html#L34-L37

**Comment by ChaseBurnett** [comment]
Not sure if you can see this but which tag should the footer and main be inside of? the body tag?
